/**
 * CHUP / Offcode — Domain Linguistic Vocabulary
 *
 * Defines pure linguistic vocabulary and canonical concept terms.
 * Strict Architectural Separation:
 * - This file contains ZERO routing rules (no concept-combination logic).
 * - This file contains ZERO solver dispatch hints.
 * - Categorizes vocabulary into words, protected short tokens, and canonical phrases.
 */

export interface CanonicalPhraseDefinition {
  phrase: string;
  canonical: string;
  tokenCount: number;
  category: 'data_structure' | 'operation' | 'qualifier' | 'numerical_method' | 'algorithm' | 'linear_algebra';
}

/**
 * Vocabulary organized by linguistic and domain category.
 */
export const VOCABULARY_BY_CATEGORY = {
  data_structures: [
    'singly', 'doubly', 'circular', 'linked', 'list', 'lists', 'stack', 'stacks',
    'queue', 'queues', 'deque', 'deques', 'tree', 'trees', 'binary', 'bst', 'heap', 'heaps',
    'graph', 'graphs', 'table', 'hash', 'map', 'set', 'array', 'arrays', 'vector',
    'vectors', 'polynomial', 'polynomials', 'segment', 'fenwick', 'trie', 'dsu', 'node', 'nodes',
    'disjoint', 'union', 'parentheses', 'parenthesis', 'postfix', 'prefix', 'infix', 'josephus',
    'palindrome', 'brackets', 'student', 'records', 'database'
  ],
  operations: [
    'insert', 'inserting', 'insertion', 'add', 'adding', 'addition', 'prepend', 'append',
    'delete', 'deleting', 'deletion', 'remove', 'removing', 'removal', 'erase', 'pop', 'push',
    'enqueue', 'dequeue', 'peek', 'traverse', 'traversing', 'traversal', 'display', 'displaying',
    'print', 'printing', 'show', 'showing', 'reverse', 'reversing', 'reversal', 'invert',
    'search', 'searching', 'find', 'finding', 'lookup', 'locate', 'count', 'counting',
    'create', 'creating', 'creation', 'implement', 'implementing', 'build', 'building',
    'construct', 'sort', 'sorting', 'update', 'updates', 'updating', 'rotate', 'merge', 'heapify',
    'query', 'queries', 'identify', 'identifying', 'interleave', 'interleaving'
  ],
  qualifiers: [
    'head', 'tail', 'beginning', 'end', 'front', 'rear', 'start', 'top', 'bottom',
    'after', 'before', 'position', 'positions', 'index', 'value', 'element', 'item', 'key', 'data',
    'next', 'prev', 'previous', 'first', 'last', 'middle', 'mid', 'root', 'left', 'right',
    'cycle', 'degree', 'weight', 'unweighted', 'directed', 'undirected',
    'values', 'elements', 'indices', 'numbers', 'pairs',
    'point', 'points', 'range', 'ranges',
    'least', 'most', 'minimum', 'maximum', 'greater', 'smaller', 'equal', 'distinct', 'unique',
    'stream', 'petrol', 'gas', 'negative', 'nonrepeating'
  ],
  numerical_methods: [
    'decomposition', 'factorization', 'elimination', 'bisection', 'bisect', 'newton',
    'raphson', 'secant', 'iteration', 'iterative', 'jacobi', 'seidel', 'gauss', 'gaussian',
    'jordan', 'euler', 'runge', 'kutta', 'rk4', 'trapezoidal', 'simpson', 'lagrange',
    'interpolation', 'divided', 'difference', 'regression', 'eigenvalue', 'doolittle',
    'false', 'position', 'regula', 'falsi'
  ],
  linear_algebra: [
    'matrix', 'matrices', 'multiplication', 'inversion', 'inverse', 'eigenvalue', 'eigenvalues',
    'eigenvector', 'eigenvectors', 'determinant', 'determinants', 'identity', 'gaussian'
  ],
  algorithms: [
    'pointers', 'pointer', 'sliding', 'window', 'prefix', 'sum', 'sums', 'binary',
    'linear', 'bubble', 'quick', 'merge', 'insertion', 'selection', 'counting', 'radix',
    'dijkstra', 'floyd', 'warshall', 'dynamic', 'programming', 'greedy', 'monotonic',
    'intervals', 'frequency', 'shortest', 'path', 'topological', 'kruskal', 'prim',
    'bellman', 'ford', 'kahn'
  ]
};

/**
 * Short words (<= 4 characters or critical tokens) that must NEVER be modified by fuzzy matching.
 * Principle: False normalization is substantially more dangerous than missed normalization.
 */
export const PROTECTED_SHORT_WORDS = new Set<string>([
  'map', 'set', 'get', 'tree', 'node', 'head', 'tail', 'top', 'pop', 'min', 'max',
  'heap', 'list', 'root', 'last', 'end', 'item', 'data', 'drop', 'make', 'show',
  'walk', 'find', 'rank', 'path', 'edge', 'grid', 'pair', 'sum', 'cost', 'gcd',
  'lcm', 'bfs', 'dfs', 'sll', 'dll', 'cll', 'bst', 'dsu', 'rk4', 'fast', 'slow',
  'null', 'next', 'prev', 'push', 'size', 'full', 'peek', 'rear', 'back', 'from',
  'with', 'into', 'step', 'each', 'sort', 'code', 'loop', 'main', 'char', 'bool',
  'long', 'void', 'auto', 'base', 'case', 'read', 'free', 'stack', 'slack', 'arr',
  'bt', 'poly', 'mid', 'put'
]);

/** Backward-compatibility alias */
export const PROTECTED_WORDS = PROTECTED_SHORT_WORDS;

/**
 * Complete set of recognized single words across all domains.
 * Authoritative candidate search space for vocabulary-driven spell correction.
 */
export const VALID_VOCABULARY_WORDS = new Set<string>([
  ...VOCABULARY_BY_CATEGORY.data_structures,
  ...VOCABULARY_BY_CATEGORY.operations,
  ...VOCABULARY_BY_CATEGORY.qualifiers,
  ...VOCABULARY_BY_CATEGORY.numerical_methods,
  ...VOCABULARY_BY_CATEGORY.linear_algebra,
  ...VOCABULARY_BY_CATEGORY.algorithms
]);

/** Backward-compatibility alias */
export const VOCABULARY_WORDS = VALID_VOCABULARY_WORDS;

/**
 * Raw definitions for canonical phrases.
 * Notice: Order here does not matter; CANONICAL_PHRASES is strictly sorted by token count descending.
 */
const RAW_CANONICAL_PHRASES: Array<{ phrase: string; canonical: string; category: CanonicalPhraseDefinition['category'] }> = [
  // ── 4-Token Phrases ─────────────────────────────────────────────────────────
  { phrase: 'doubly circular linked list', canonical: 'doubly_circular_linked_list', category: 'data_structure' },
  { phrase: 'circular doubly linked list', canonical: 'doubly_circular_linked_list', category: 'data_structure' },
  { phrase: 'stack using linked list', canonical: 'stack_linked_list', category: 'data_structure' },
  { phrase: 'queue using linked list', canonical: 'queue_linked_list', category: 'data_structure' },
  { phrase: 'circular queue using array', canonical: 'circular_queue', category: 'data_structure' },
  { phrase: 'runge kutta fourth order', canonical: 'runge_kutta', category: 'numerical_method' },
  { phrase: 'runge kutta 4th order', canonical: 'runge_kutta', category: 'numerical_method' },
  { phrase: 'convert infix to postfix', canonical: 'infix_to_postfix', category: 'algorithm' },
  { phrase: 'convert infix to prefix', canonical: 'infix_to_prefix', category: 'algorithm' },
  { phrase: 'balanced parentheses check using', canonical: 'balanced_parentheses', category: 'algorithm' },
  { phrase: 'menu driven student records', canonical: 'student_records_linked_list', category: 'data_structure' },
  { phrase: 'menu driven student database', canonical: 'student_records_linked_list', category: 'data_structure' },
  { phrase: 'student database using struct', canonical: 'student_records_linked_list', category: 'data_structure' },
  { phrase: 'delete all occurrences of', canonical: 'linked_list_delete_all', category: 'operation' },
  { phrase: 'delete node given only', canonical: 'linked_list_delete_node_ptr', category: 'operation' },
  { phrase: 'delete node without head', canonical: 'linked_list_delete_node_ptr', category: 'operation' },
  { phrase: 'add two numbers stored', canonical: 'linked_list_add_two_numbers', category: 'algorithm' },
  { phrase: 'queue using two stacks', canonical: 'queue_using_stacks', category: 'data_structure' },
  { phrase: 'two stacks in one', canonical: 'two_stacks_array', category: 'data_structure' },
  { phrase: 'two stacks in an', canonical: 'two_stacks_array', category: 'data_structure' },
  { phrase: 'min stack getmin in', canonical: 'min_stack', category: 'data_structure' },
  { phrase: 'sort stack using recursion', canonical: 'sort_stack', category: 'algorithm' },
  { phrase: 'reverse stack using recursion', canonical: 'reverse_stack', category: 'algorithm' },
  { phrase: 'reverse a stack using recursion', canonical: 'reverse_stack', category: 'algorithm' },
  { phrase: 'delete middle element of stack', canonical: 'delete_middle_stack', category: 'algorithm' },
  { phrase: 'delete middle element of a', canonical: 'delete_middle_stack', category: 'algorithm' },
  { phrase: 'delete middle node of stack', canonical: 'delete_middle_stack', category: 'algorithm' },
  { phrase: 'next greater element in array', canonical: 'next_greater_element', category: 'algorithm' },
  { phrase: 'next greater element using stack', canonical: 'next_greater_element', category: 'algorithm' },
  { phrase: 'next smaller element in array', canonical: 'next_smaller_element', category: 'algorithm' },
  { phrase: 'next smaller element using stack', canonical: 'next_smaller_element', category: 'algorithm' },
  { phrase: 'previous greater element using stack', canonical: 'previous_greater_element', category: 'algorithm' },
  { phrase: 'previous smaller element using stack', canonical: 'previous_smaller_element', category: 'algorithm' },
  { phrase: 'stock span problem using stack', canonical: 'stock_span', category: 'algorithm' },
  { phrase: 'largest rectangle in histogram using', canonical: 'largest_rectangle_histogram', category: 'algorithm' },
  { phrase: 'largest rectangle in histogram', canonical: 'largest_rectangle_histogram', category: 'algorithm' },
  { phrase: 'largest rectangular area in histogram', canonical: 'largest_rectangle_histogram', category: 'algorithm' },
  { phrase: 'trapping rain water using stack', canonical: 'trapping_rain_water_stack', category: 'algorithm' },
  { phrase: 'celebrity problem using stack', canonical: 'celebrity_problem', category: 'algorithm' },
  { phrase: 'find celebrity in a party', canonical: 'celebrity_problem', category: 'algorithm' },
  { phrase: 'convert postfix to infix', canonical: 'postfix_to_infix', category: 'algorithm' },
  { phrase: 'convert prefix to infix', canonical: 'prefix_to_infix', category: 'algorithm' },
  { phrase: 'convert postfix to prefix', canonical: 'postfix_to_prefix', category: 'algorithm' },
  { phrase: 'convert prefix to postfix', canonical: 'prefix_to_postfix', category: 'algorithm' },
  { phrase: 'evaluate infix expression using stack', canonical: 'evaluate_infix', category: 'algorithm' },
  { phrase: 'evaluate infix expression using', canonical: 'evaluate_infix', category: 'algorithm' },
  { phrase: 'check for redundant brackets', canonical: 'redundant_brackets', category: 'algorithm' },
  { phrase: 'check redundant brackets using stack', canonical: 'redundant_brackets', category: 'algorithm' },
  { phrase: 'longest valid parentheses using stack', canonical: 'longest_valid_parentheses', category: 'algorithm' },
  { phrase: 'longest valid parentheses substring', canonical: 'longest_valid_parentheses', category: 'algorithm' },
  { phrase: 'implement stack using two queues', canonical: 'stack_using_queues', category: 'data_structure' },
  { phrase: 'implement stack using queues', canonical: 'stack_using_queues', category: 'data_structure' },
  { phrase: 'stack using two queues', canonical: 'stack_using_queues', category: 'data_structure' },
  { phrase: 'k stacks in an array', canonical: 'k_stacks_array', category: 'data_structure' },
  { phrase: 'k stacks in a single', canonical: 'k_stacks_array', category: 'data_structure' },
  { phrase: 'reverse string using stack', canonical: 'reverse_string_stack', category: 'algorithm' },
  { phrase: 'reverse array using stack', canonical: 'reverse_string_stack', category: 'algorithm' },
  { phrase: 'decimal to binary conversion', canonical: 'decimal_to_binary_stack', category: 'algorithm' },
  { phrase: 'decimal to binary using', canonical: 'decimal_to_binary_stack', category: 'algorithm' },
  { phrase: 'palindrome check using stack', canonical: 'reverse_string_stack', category: 'algorithm' },
  { phrase: 'josephus problem using circular', canonical: 'josephus_problem', category: 'algorithm' },
  { phrase: 'polynomial addition using linked', canonical: 'polynomial', category: 'data_structure' },
  { phrase: 'polynomial multiplication using linked', canonical: 'polynomial', category: 'data_structure' },
  { phrase: 'reverse first k elements of queue', canonical: 'reverse_first_k_queue', category: 'algorithm' },
  { phrase: 'reverse first k elements of a queue', canonical: 'reverse_first_k_queue', category: 'algorithm' },
  { phrase: 'reverse first k elements in queue', canonical: 'reverse_first_k_queue', category: 'algorithm' },
  { phrase: 'reverse first k elements', canonical: 'reverse_first_k_queue', category: 'algorithm' },
  { phrase: 'generate binary numbers using queue', canonical: 'generate_binary_numbers', category: 'algorithm' },
  { phrase: 'generate binary numbers from 1 to', canonical: 'generate_binary_numbers', category: 'algorithm' },
  { phrase: 'first non repeating character stream', canonical: 'first_non_repeating_char', category: 'algorithm' },
  { phrase: 'first non repeating character in', canonical: 'first_non_repeating_char', category: 'algorithm' },
  { phrase: 'first non-repeating character in stream', canonical: 'first_non_repeating_char', category: 'algorithm' },
  { phrase: 'sliding window maximum using deque', canonical: 'sliding_window_maximum', category: 'algorithm' },
  { phrase: 'sliding window maximum using queue', canonical: 'sliding_window_maximum', category: 'algorithm' },
  { phrase: 'sliding window maximum in array', canonical: 'sliding_window_maximum', category: 'algorithm' },
  { phrase: 'first negative integer in window', canonical: 'first_negative_window', category: 'algorithm' },
  { phrase: 'first negative in every window', canonical: 'first_negative_window', category: 'algorithm' },
  { phrase: 'first negative integer in every', canonical: 'first_negative_window', category: 'algorithm' },
  { phrase: 'interleave first half with second', canonical: 'interleave_queue', category: 'algorithm' },
  { phrase: 'interleave the first half of', canonical: 'interleave_queue', category: 'algorithm' },
  { phrase: 'sort queue using a stack', canonical: 'queue_sort_using_stack', category: 'algorithm' },
  { phrase: 'sort queue using stack', canonical: 'queue_sort_using_stack', category: 'algorithm' },
  { phrase: 'sort a queue using stack', canonical: 'queue_sort_using_stack', category: 'algorithm' },
  { phrase: 'linear queue using array', canonical: 'linear_queue', category: 'data_structure' },
  { phrase: 'double ended queue using', canonical: 'deque', category: 'data_structure' },
  { phrase: 'priority queue using array', canonical: 'priority_queue', category: 'data_structure' },
  { phrase: 'priority queue using heap', canonical: 'priority_queue', category: 'data_structure' },
  { phrase: 'circular tour using queue', canonical: 'circular_tour', category: 'algorithm' },
  { phrase: 'petrol pump tour using queue', canonical: 'circular_tour', category: 'algorithm' },
  { phrase: 'petrol pump tour problem', canonical: 'circular_tour', category: 'algorithm' },
  { phrase: 'gas station problem using queue', canonical: 'circular_tour', category: 'algorithm' },
  { phrase: 'reverse a queue using recursion', canonical: 'reverse_queue', category: 'algorithm' },
  { phrase: 'reverse queue using recursion', canonical: 'reverse_queue', category: 'algorithm' },

  // ── 3-Token Phrases ─────────────────────────────────────────────────────────
  { phrase: 'singly linked list', canonical: 'singly_linked_list', category: 'data_structure' },
  { phrase: 'doubly linked list', canonical: 'doubly_linked_list', category: 'data_structure' },
  { phrase: 'double linked list', canonical: 'doubly_linked_list', category: 'data_structure' },
  { phrase: 'circular linked list', canonical: 'circular_linked_list', category: 'data_structure' },
  { phrase: 'doubly circular list', canonical: 'doubly_circular_linked_list', category: 'data_structure' },
  { phrase: 'circular doubly list', canonical: 'doubly_circular_linked_list', category: 'data_structure' },
  { phrase: 'student records database', canonical: 'student_records_linked_list', category: 'data_structure' },
  { phrase: 'student database struct', canonical: 'student_records_linked_list', category: 'data_structure' },
  { phrase: 'menu driven program', canonical: 'menu', category: 'operation' },
  { phrase: 'balanced parentheses check', canonical: 'balanced_parentheses', category: 'algorithm' },
  { phrase: 'check balanced parentheses', canonical: 'balanced_parentheses', category: 'algorithm' },
  { phrase: 'check balanced brackets', canonical: 'balanced_parentheses', category: 'algorithm' },
  { phrase: 'valid parentheses stack', canonical: 'balanced_parentheses', category: 'algorithm' },
  { phrase: 'infix to postfix', canonical: 'infix_to_postfix', category: 'algorithm' },
  { phrase: 'infix to prefix', canonical: 'infix_to_prefix', category: 'algorithm' },
  { phrase: 'evaluate postfix expression', canonical: 'postfix_evaluation', category: 'algorithm' },
  { phrase: 'evaluate prefix expression', canonical: 'prefix_evaluation', category: 'algorithm' },
  { phrase: 'postfix expression evaluation', canonical: 'postfix_evaluation', category: 'algorithm' },
  { phrase: 'prefix expression evaluation', canonical: 'prefix_evaluation', category: 'algorithm' },
  { phrase: 'reverse string stack', canonical: 'reverse_string_stack', category: 'algorithm' },
  { phrase: 'decimal to binary', canonical: 'decimal_to_binary_stack', category: 'algorithm' },
  { phrase: 'convert decimal to', canonical: 'decimal_to_binary_stack', category: 'algorithm' },
  { phrase: 'queue using stack', canonical: 'queue_using_stacks', category: 'data_structure' },
  { phrase: 'two stacks array', canonical: 'two_stacks_array', category: 'data_structure' },
  { phrase: 'implement min stack', canonical: 'min_stack', category: 'data_structure' },
  { phrase: 'min stack getmin', canonical: 'min_stack', category: 'data_structure' },
  { phrase: 'sort stack recursion', canonical: 'sort_stack', category: 'algorithm' },
  { phrase: 'reverse stack recursion', canonical: 'reverse_stack', category: 'algorithm' },
  { phrase: 'reverse a stack', canonical: 'reverse_stack', category: 'algorithm' },
  { phrase: 'delete middle element', canonical: 'delete_middle_stack', category: 'algorithm' },
  { phrase: 'delete middle stack', canonical: 'delete_middle_stack', category: 'algorithm' },
  { phrase: 'delete middle node', canonical: 'delete_middle_stack', category: 'algorithm' },
  { phrase: 'next greater element', canonical: 'next_greater_element', category: 'algorithm' },
  { phrase: 'next smaller element', canonical: 'next_smaller_element', category: 'algorithm' },
  { phrase: 'previous greater element', canonical: 'previous_greater_element', category: 'algorithm' },
  { phrase: 'previous smaller element', canonical: 'previous_smaller_element', category: 'algorithm' },
  { phrase: 'stock span problem', canonical: 'stock_span', category: 'algorithm' },
  { phrase: 'stock span stack', canonical: 'stock_span', category: 'algorithm' },
  { phrase: 'largest rectangle histogram', canonical: 'largest_rectangle_histogram', category: 'algorithm' },
  { phrase: 'trapping rain water', canonical: 'trapping_rain_water_stack', category: 'algorithm' },
  { phrase: 'celebrity problem stack', canonical: 'celebrity_problem', category: 'algorithm' },
  { phrase: 'find celebrity party', canonical: 'celebrity_problem', category: 'algorithm' },
  { phrase: 'postfix to infix', canonical: 'postfix_to_infix', category: 'algorithm' },
  { phrase: 'prefix to infix', canonical: 'prefix_to_infix', category: 'algorithm' },
  { phrase: 'postfix to prefix', canonical: 'postfix_to_prefix', category: 'algorithm' },
  { phrase: 'prefix to postfix', canonical: 'prefix_to_postfix', category: 'algorithm' },
  { phrase: 'evaluate infix expression', canonical: 'evaluate_infix', category: 'algorithm' },
  { phrase: 'evaluate infix stack', canonical: 'evaluate_infix', category: 'algorithm' },
  { phrase: 'check redundant brackets', canonical: 'redundant_brackets', category: 'algorithm' },
  { phrase: 'check redundant parentheses', canonical: 'redundant_brackets', category: 'algorithm' },
  { phrase: 'redundant brackets stack', canonical: 'redundant_brackets', category: 'algorithm' },
  { phrase: 'longest valid parentheses', canonical: 'longest_valid_parentheses', category: 'algorithm' },
  { phrase: 'stack two queues', canonical: 'stack_using_queues', category: 'data_structure' },
  { phrase: 'stack using queue', canonical: 'stack_using_queues', category: 'data_structure' },
  { phrase: 'k stacks array', canonical: 'k_stacks_array', category: 'data_structure' },
  { phrase: 'floyd cycle detection', canonical: 'linked_list_cycle_detection', category: 'algorithm' },
  { phrase: 'detect cycle in', canonical: 'linked_list_cycle_detection', category: 'algorithm' },
  { phrase: 'find cycle start', canonical: 'linked_list_cycle_start', category: 'algorithm' },
  { phrase: 'remove cycle from', canonical: 'linked_list_remove_cycle', category: 'algorithm' },
  { phrase: 'remove cycle linked', canonical: 'linked_list_remove_cycle', category: 'algorithm' },
  { phrase: 'find middle node', canonical: 'linked_list_middle', category: 'algorithm' },
  { phrase: 'find middle element', canonical: 'linked_list_middle', category: 'algorithm' },
  { phrase: 'nth node from', canonical: 'linked_list_nth_from_end', category: 'algorithm' },
  { phrase: 'remove duplicates from', canonical: 'linked_list_remove_duplicates', category: 'algorithm' },
  { phrase: 'merge sorted lists', canonical: 'linked_list_merge_sorted', category: 'algorithm' },
  { phrase: 'merge two sorted', canonical: 'linked_list_merge_sorted', category: 'algorithm' },
  { phrase: 'split into two', canonical: 'linked_list_split_halves', category: 'algorithm' },
  { phrase: 'split linked list', canonical: 'linked_list_split_halves', category: 'algorithm' },
  { phrase: 'print in reverse', canonical: 'linked_list_print_reverse', category: 'operation' },
  { phrase: 'print reverse linked', canonical: 'linked_list_print_reverse', category: 'operation' },
  { phrase: 'check palindrome list', canonical: 'linked_list_palindrome', category: 'algorithm' },
  { phrase: 'check if palindrome', canonical: 'linked_list_palindrome', category: 'algorithm' },
  { phrase: 'palindrome linked list', canonical: 'linked_list_palindrome', category: 'algorithm' },
  { phrase: 'rotate linked list', canonical: 'linked_list_rotate', category: 'algorithm' },
  { phrase: 'delete all occurrences', canonical: 'linked_list_delete_all', category: 'operation' },
  { phrase: 'delete without head', canonical: 'linked_list_delete_node_ptr', category: 'operation' },
  { phrase: 'sum of nodes', canonical: 'linked_list_sum', category: 'operation' },
  { phrase: 'sum of list', canonical: 'linked_list_sum', category: 'operation' },
  { phrase: 'josephus problem circular', canonical: 'josephus_problem', category: 'algorithm' },
  { phrase: 'josephus problem using', canonical: 'josephus_problem', category: 'algorithm' },
  { phrase: 'add two numbers', canonical: 'linked_list_add_two_numbers', category: 'algorithm' },
  { phrase: 'add polynomials using', canonical: 'polynomial', category: 'data_structure' },
  { phrase: 'polynomial addition using', canonical: 'polynomial', category: 'data_structure' },
  { phrase: 'polynomial multiplication using', canonical: 'polynomial', category: 'data_structure' },
  { phrase: 'binary search tree', canonical: 'bst', category: 'data_structure' },
  { phrase: 'stack using array', canonical: 'stack_array', category: 'data_structure' },
  { phrase: 'fixed point iteration', canonical: 'fixed_point_iteration', category: 'numerical_method' },
  { phrase: 'gauss jordan elimination', canonical: 'gauss_jordan', category: 'numerical_method' },
  { phrase: 'gauss seidel iteration', canonical: 'gauss_seidel', category: 'numerical_method' },
  { phrase: 'jacobi iterative method', canonical: 'jacobi', category: 'numerical_method' },
  { phrase: 'runge kutta method', canonical: 'runge_kutta', category: 'numerical_method' },
  { phrase: 'runge kutta 4', canonical: 'runge_kutta', category: 'numerical_method' },
  { phrase: 'disjoint set union', canonical: 'dsu', category: 'data_structure' },
  { phrase: 'nearest smaller values', canonical: 'nearest_smaller_values', category: 'algorithm' },
  { phrase: 'newton forward interpolation', canonical: 'newton_forward', category: 'numerical_method' },
  { phrase: 'newton backward interpolation', canonical: 'newton_backward', category: 'numerical_method' },

  // ── 2-Token Phrases ─────────────────────────────────────────────────────────
  { phrase: 'menu driven', canonical: 'menu', category: 'operation' },
  { phrase: 'menu program', canonical: 'menu', category: 'operation' },
  { phrase: 'interactive menu', canonical: 'menu', category: 'operation' },
  { phrase: 'linked list', canonical: 'linked_list', category: 'data_structure' },
  { phrase: 'singly linked', canonical: 'singly_linked_list', category: 'data_structure' },
  { phrase: 'doubly linked', canonical: 'doubly_linked_list', category: 'data_structure' },
  { phrase: 'circular list', canonical: 'circular_linked_list', category: 'data_structure' },
  { phrase: 'doubly circular', canonical: 'doubly_circular_linked_list', category: 'data_structure' },
  { phrase: 'circular doubly', canonical: 'doubly_circular_linked_list', category: 'data_structure' },
  { phrase: 'circular queue', canonical: 'circular_queue', category: 'data_structure' },
  { phrase: 'linear queue', canonical: 'linear_queue', category: 'data_structure' },
  { phrase: 'binary tree', canonical: 'binary_tree', category: 'data_structure' },
  { phrase: 'search tree', canonical: 'bst', category: 'data_structure' },
  { phrase: 'hash table', canonical: 'hash_table', category: 'data_structure' },
  { phrase: 'hash map', canonical: 'hash_table', category: 'data_structure' },
  { phrase: 'hash set', canonical: 'hash_table', category: 'data_structure' },
  { phrase: 'priority queue', canonical: 'priority_queue', category: 'data_structure' },
  { phrase: 'double ended', canonical: 'deque', category: 'data_structure' },
  { phrase: 'reverse queue', canonical: 'reverse_queue', category: 'algorithm' },
  { phrase: 'interleave queue', canonical: 'interleave_queue', category: 'algorithm' },
  { phrase: 'circular tour', canonical: 'circular_tour', category: 'algorithm' },
  { phrase: 'gas station', canonical: 'circular_tour', category: 'algorithm' },
  { phrase: 'sort queue', canonical: 'queue_sort_using_stack', category: 'algorithm' },
  { phrase: 'binary numbers', canonical: 'generate_binary_numbers', category: 'algorithm' },
  { phrase: 'window maximum', canonical: 'sliding_window_maximum', category: 'algorithm' },
  { phrase: 'negative window', canonical: 'first_negative_window', category: 'algorithm' },
  { phrase: 'min heap', canonical: 'heap', category: 'data_structure' },
  { phrase: 'max heap', canonical: 'heap', category: 'data_structure' },
  { phrase: 'adjacency list', canonical: 'graph', category: 'data_structure' },
  { phrase: 'adjacency matrix', canonical: 'graph', category: 'data_structure' },
  { phrase: 'lu decomposition', canonical: 'lu_decomposition', category: 'numerical_method' },
  { phrase: 'lu factorization', canonical: 'lu_decomposition', category: 'numerical_method' },
  { phrase: 'lu method', canonical: 'lu_decomposition', category: 'numerical_method' },
  { phrase: 'gauss elimination', canonical: 'gauss_elimination', category: 'numerical_method' },
  { phrase: 'gaussian elimination', canonical: 'gauss_elimination', category: 'numerical_method' },
  { phrase: 'gauss jordan', canonical: 'gauss_jordan', category: 'numerical_method' },
  { phrase: 'gauss seidel', canonical: 'gauss_seidel', category: 'numerical_method' },
  { phrase: 'newton raphson', canonical: 'newton_raphson', category: 'numerical_method' },
  { phrase: 'secant method', canonical: 'secant', category: 'numerical_method' },
  { phrase: 'false position', canonical: 'false_position', category: 'numerical_method' },
  { phrase: 'regula falsi', canonical: 'false_position', category: 'numerical_method' },
  { phrase: 'bisection method', canonical: 'bisection', category: 'numerical_method' },
  { phrase: 'runge kutta', canonical: 'runge_kutta', category: 'numerical_method' },
  { phrase: 'euler method', canonical: 'euler', category: 'numerical_method' },
  { phrase: 'modified euler', canonical: 'euler', category: 'numerical_method' },
  { phrase: 'trapezoidal rule', canonical: 'trapezoidal', category: 'numerical_method' },
  { phrase: 'simpson rule', canonical: 'simpson', category: 'numerical_method' },
  { phrase: 'two pointers', canonical: 'two_pointers', category: 'algorithm' },
  { phrase: 'two pointer', canonical: 'two_pointers', category: 'algorithm' },
  { phrase: 'sliding window', canonical: 'sliding_window', category: 'algorithm' },
  { phrase: 'prefix sum', canonical: 'prefix_sum', category: 'algorithm' },
  { phrase: 'binary search', canonical: 'binary_search', category: 'algorithm' },
  { phrase: 'linear search', canonical: 'linear_search', category: 'algorithm' },
  { phrase: 'bubble sort', canonical: 'bubble_sort', category: 'algorithm' },
  { phrase: 'insertion sort', canonical: 'insertion_sort', category: 'algorithm' },
  { phrase: 'selection sort', canonical: 'selection_sort', category: 'algorithm' },
  { phrase: 'merge sort', canonical: 'merge_sort', category: 'algorithm' },
  { phrase: 'quick sort', canonical: 'quick_sort', category: 'algorithm' },
  { phrase: 'heap sort', canonical: 'heap_sort', category: 'algorithm' },
  { phrase: 'counting sort', canonical: 'counting_sort', category: 'algorithm' },
  { phrase: 'radix sort', canonical: 'radix_sort', category: 'algorithm' },
  { phrase: 'segment tree', canonical: 'segment_tree', category: 'data_structure' },
  { phrase: 'fenwick tree', canonical: 'fenwick_tree', category: 'data_structure' },
  { phrase: 'monotonic stack', canonical: 'monotonic_stack', category: 'data_structure' },
  { phrase: 'dynamic programming', canonical: 'dynamic_programming', category: 'algorithm' },
  { phrase: 'next greater', canonical: 'next_greater', category: 'algorithm' },
  { phrase: 'next smaller', canonical: 'next_smaller_element', category: 'algorithm' },
  { phrase: 'previous greater', canonical: 'previous_greater_element', category: 'algorithm' },
  { phrase: 'previous smaller', canonical: 'previous_smaller_element', category: 'algorithm' },
  { phrase: 'stock span', canonical: 'stock_span', category: 'algorithm' },
  { phrase: 'celebrity problem', canonical: 'celebrity_problem', category: 'algorithm' },
  { phrase: 'reverse stack', canonical: 'reverse_stack', category: 'algorithm' },
  { phrase: 'evaluate infix', canonical: 'evaluate_infix', category: 'algorithm' },
  { phrase: 'infix evaluation', canonical: 'evaluate_infix', category: 'algorithm' },
  { phrase: 'redundant brackets', canonical: 'redundant_brackets', category: 'algorithm' },
  { phrase: 'redundant parentheses', canonical: 'redundant_brackets', category: 'algorithm' },
  { phrase: 'k stacks', canonical: 'k_stacks_array', category: 'data_structure' },
  { phrase: 'daily temperatures', canonical: 'daily_temperatures', category: 'algorithm' },
  { phrase: 'lru cache', canonical: 'lru_cache', category: 'data_structure' },
  { phrase: 'lfu cache', canonical: 'lfu_cache', category: 'data_structure' },
  { phrase: 'matrix multiplication', canonical: 'matrix_multiplication', category: 'linear_algebra' },
  { phrase: 'matrix inversion', canonical: 'matrix_inversion', category: 'linear_algebra' },
  { phrase: 'floyd warshall', canonical: 'floyd_warshall', category: 'algorithm' },
  { phrase: 'shortest path', canonical: 'shortest_path', category: 'algorithm' },

  // ── 1-Token Abbreviations & Key Terms ───────────────────────────────────────
  { phrase: 'sll', canonical: 'singly_linked_list', category: 'data_structure' },
  { phrase: 'dll', canonical: 'doubly_linked_list', category: 'data_structure' },
  { phrase: 'cll', canonical: 'circular_linked_list', category: 'data_structure' },
  { phrase: 'dcll', canonical: 'doubly_circular_linked_list', category: 'data_structure' },
  { phrase: 'bst', canonical: 'bst', category: 'data_structure' },
  { phrase: 'dsu', canonical: 'dsu', category: 'data_structure' },
  { phrase: 'rk4', canonical: 'runge_kutta', category: 'numerical_method' },
  { phrase: 'stack', canonical: 'stack', category: 'data_structure' },
  { phrase: 'queue', canonical: 'queue', category: 'data_structure' },
  { phrase: 'deque', canonical: 'deque', category: 'data_structure' },
  { phrase: 'heap', canonical: 'heap', category: 'data_structure' },
  { phrase: 'tree', canonical: 'tree', category: 'data_structure' },
  { phrase: 'graph', canonical: 'graph', category: 'data_structure' },
  { phrase: 'polynomial', canonical: 'polynomial', category: 'data_structure' },
  { phrase: 'array', canonical: 'array', category: 'data_structure' },
  { phrase: 'vector', canonical: 'array', category: 'data_structure' },
  { phrase: 'insert', canonical: 'insert', category: 'operation' },
  { phrase: 'delete', canonical: 'delete', category: 'operation' },
  { phrase: 'remove', canonical: 'delete', category: 'operation' },
  { phrase: 'search', canonical: 'search', category: 'operation' },
  { phrase: 'display', canonical: 'display', category: 'operation' },
  { phrase: 'traverse', canonical: 'display', category: 'operation' },
  { phrase: 'print', canonical: 'display', category: 'operation' },
  { phrase: 'reverse', canonical: 'reverse', category: 'operation' },
  { phrase: 'create', canonical: 'create', category: 'operation' },
  { phrase: 'implement', canonical: 'create', category: 'operation' },
  { phrase: 'push', canonical: 'push', category: 'operation' },
  { phrase: 'pop', canonical: 'pop', category: 'operation' },
  { phrase: 'enqueue', canonical: 'enqueue', category: 'operation' },
  { phrase: 'dequeue', canonical: 'dequeue', category: 'operation' },
  { phrase: 'peek', canonical: 'peek', category: 'operation' },
  { phrase: 'count', canonical: 'count', category: 'operation' },
  { phrase: 'sort', canonical: 'sort', category: 'operation' },
  { phrase: 'head', canonical: 'head', category: 'qualifier' },
  { phrase: 'beginning', canonical: 'head', category: 'qualifier' },
  { phrase: 'front', canonical: 'head', category: 'qualifier' },
  { phrase: 'tail', canonical: 'tail', category: 'qualifier' },
  { phrase: 'end', canonical: 'tail', category: 'qualifier' },
  { phrase: 'node', canonical: 'node', category: 'qualifier' },
  { phrase: 'value', canonical: 'value', category: 'qualifier' },
  { phrase: 'element', canonical: 'node', category: 'qualifier' },
  { phrase: 'position', canonical: 'position', category: 'qualifier' },
  { phrase: 'index', canonical: 'position', category: 'qualifier' },
  { phrase: 'after', canonical: 'after', category: 'qualifier' },
  { phrase: 'before', canonical: 'before', category: 'qualifier' },
  { phrase: 'bisection', canonical: 'bisection', category: 'numerical_method' },
  { phrase: 'secant', canonical: 'secant', category: 'numerical_method' },
  { phrase: 'jacobi', canonical: 'jacobi', category: 'numerical_method' },
  { phrase: 'trapezoidal', canonical: 'trapezoidal', category: 'numerical_method' },
  { phrase: 'simpson', canonical: 'simpson', category: 'numerical_method' },
  { phrase: 'euler', canonical: 'euler', category: 'numerical_method' },
  { phrase: 'lagrange', canonical: 'lagrange', category: 'numerical_method' }
];

/**
 * Canonical phrases strictly sorted by token count descending.
 * Invariant: Longest-match-first priority.
 */
export const CANONICAL_PHRASES: CanonicalPhraseDefinition[] = RAW_CANONICAL_PHRASES
  .map(def => ({
    ...def,
    tokenCount: def.phrase.trim().split(/\s+/).length
  }))
  .sort((a, b) => b.tokenCount - a.tokenCount || b.phrase.length - a.phrase.length);
